# Spam Classification using K-Nearest Neighbors

## Data Import

In [1]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
spambase = fetch_ucirepo(id=94) 
  
# data (as pandas dataframes) 
X = spambase.data.features 
y = spambase.data.targets

## Exploratory Data Analysis

In [2]:
type(X)

pandas.DataFrame

In [3]:
type(y)

pandas.DataFrame

In [4]:
import pandas as pd

data = pd.concat([X, y], axis=1)
data.head()

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total,Class
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1

In [5]:
# Check for null values
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   word_freq_make              4601 non-null   float64
 1   word_freq_address           4601 non-null   float64
 2   word_freq_all               4601 non-null   float64
 3   word_freq_3d                4601 non-null   float64
 4   word_freq_our               4601 non-null   float64
 5   word_freq_over              4601 non-null   float64
 6   word_freq_remove            4601 non-null   float64
 7   word_freq_internet          4601 non-null   float64
 8   word_freq_order             4601 non-null   float64
 9   word_freq_mail              4601 non-null   float64
 10  word_freq_receive           4601 non-null   float64
 11  word_freq_will              4601 non-null   float64
 12  word_freq_people            4601 non-null   float64
 13  word_freq_report            4601 non-null   float64
 14  word_freq_addresses         4601 non-null   float64
 15  word_freq_free              4601 non-null   float64
 16  word_freq_business          4601 non-null   float64
 17  word_freq_email             4601 non-null   float64
 18  word_freq_you               4601 non-null   float64
 19  word_freq_credit            4601 non-null   float64
 20  word_freq_your              4601 non-null   float64
 21  word_freq_font              4601 non-null   float64
 22  word_freq_000               4601 non-null   float64
 23  word_freq_money             4601 non-null   float64
 24  word_freq_hp                4601 non-null   float64
 25  word_freq_hpl               4601 non-null   float64
 26  word_freq_george            4601 non-null   float64
 27  word_freq_650               4601 non-null   float64
 28  word_freq_lab               4601 non-null   float64
 29  word_freq_labs              4601 non-null   float64
 30  word_freq_telnet            4601 non-null   float64
 31  word_freq_857               4601 non-null   float64
 32  word_freq_data              4601 non-null   float64
 33  word_freq_415               4601 non-null   float64
 34  word_freq_85                4601 non-null   float64
 35  word_freq_technology        4601 non-null   float64
 36  word_freq_1999              4601 non-null   float64
 37  word_freq_parts             4601 non-null   float64
 38  word_freq_pm                4601 non-null   float64
 39  word_freq_direct            4601 non-null   float64
 40  word_freq_cs                4601 non-null   float64
 41  word_freq_meeting           4601 non-null   float64
 42  word_freq_original          4601 non-null   float64
 43  word_freq_project           4601 non-null   float64
 44  word_freq_re                4601 non-null   float64
 45  word_freq_edu               4601 non-null   float64
 46  word_freq_table             4601 non-null   float64
 47  word_freq_conference        4601 non-null   float64
 48  char_freq_;                 4601 non-null   float64
 49  char_freq_(                 4601 non-null   float64
 50  char_freq_[                 4601 non-null   float64
 51  char_freq_!                 4601 non-null   float64
 52  char_freq_$                 4601 non-null   float64
 53  char_freq_#                 4601 non-null   float64
 54  capital_run_length_average  4601 non-null   float64
 55  capital_run_length_longest  4601 non-null   int64
 56  capital_run_length_total    4601 non-null   int64
 57  Class                       4601 non-null   int64
dtypes: float64(55), int64(3)
memory usage: 2.0 MB

In [6]:
data.isnull().any()

word_freq_make                False
word_freq_address             False
word_freq_all                 False
word_freq_3d                  False
word_freq_our                 False
word_freq_over                False
word_freq_remove              False
word_freq_internet            False
word_freq_order               False
word_freq_mail                False
word_freq_receive             False
word_freq_will                False
word_freq_people              False
word_freq_report              False
word_freq_addresses           False
word_freq_free                False
word_freq_business            False
word_freq_email               False
word_freq_you                 False
word_freq_credit              False
word_freq_your                False
word_freq_font                False
word_freq_000                 False
word_freq_money               False
word_freq_hp                  False
word_freq_hpl                 False
word_freq_george              False
word_freq_650                 False
word_freq_lab                 False
word_freq_labs                False
word_freq_telnet              False
word_freq_857                 False
word_freq_data                False
word_freq_415                 False
word_freq_85                  False
word_freq_technology          False
word_freq_1999                False
word_freq_parts               False
word_freq_pm                  False
word_freq_direct              False
word_freq_cs                  False
word_freq_meeting             False
word_freq_original            False
word_freq_project             False
word_freq_re                  False
word_freq_edu                 False
word_freq_table               False
word_freq_conference          False
char_freq_;                   False
char_freq_(                   False
char_freq_[                   False
char_freq_!                   False
char_freq_$                   False
char_freq_#                   False
capital_run_length_average    False
capital_run_length_longest    False
capital_run_length_total      False
Class                         False
dtype: bool

In [7]:
# Check for duplicates
data.duplicated().any()

np.True_

In [8]:
duplicate_indices = data.duplicated()  # Boolean Series
duplicate_indices

0       False
1       False
2       False
3       False
4       False
        ...
4596    False
4597    False
4598    False
4599    False
4600    False
Length: 4601, dtype: bool

In [9]:
data[duplicate_indices]

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total,Class
26,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.000,0.196,0.000,0.392,0.196,0.0,5.466,22,82,1
103,0.0,0.0,0.64,0.0,0.0,0.64,0.0,0.0,0.0,0.0,...,0.094,0.189,0.284,0.662,0.000,0.0,10.068,131,292,1
104,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.305,0.611,0.000,1.529,0.000,0.0,5.500,22,66,1
105,0.0,0.0,0.64,0.0,0.0,0.64,0.0,0.0,0.0,0.0,...,0.094,0.189,0.284,0.662,0.000,0.0,10.068,131,292,1
106,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.305,0.611,0.000,1.529,0.000,0.0,5.500,22,66,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4439,0.0,0.0,0.74,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.036,0.147,0.000,0.147,0.000,0.0,2.587,55,282,0
4441,0.0,0.0,0.74,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.036,0.147,0.000,0.147,0.000,0.0,2.587,55,282,0
4537,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.000,0.000,0.000,0.000,0.000,0.0,1.000,1,6,0
4541,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.000,0.000,0.000,0.000,0.000,0.0,1.000,1,2,0
4550,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.0,0.0,...,0.000,0.000,0.000,0.000,0.000,0.0,2.000,3,4,0

In [10]:
4601 - 391

4210

In [11]:
data = data.drop_duplicates()
data

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,char_freq_;,char_freq_(,char_freq_[,char_freq_!,char_freq_$,char_freq_#,capital_run_length_average,capital_run_length_longest,capital_run_length_total,Class
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.000,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.010,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.000,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.000,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4596,0.31,0.00,0.62,0.0,0.00,0.31,0.00,0.00,0.00,0.00,...,0.000,0.232,0.0,0.000,0.000,0.000,1.142,3,88,0
4597,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.353,0.000,0.000,1.555,4,14,0
4598,0.30,0.00,0.30,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.102,0.718,0.0,0.000,0.000,0.000,1.404,6,118,0
4599,0.96,0.00,0.00,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.000,0.057,0.0,0.000,0.000,0.000,1.147,5,78,0
4600,0.00,0.00,0.65,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.125,0.000,0.000,1.250,5,40,0

In [12]:
# Distrubtion of Emails
data['Class'].value_counts(normalize=True)

Class
0    0.601188
1    0.398812
Name: proportion, dtype: float64

## Train-test Split

In [13]:
from sklearn.model_selection import train_test_split

target_column = "Class"
features = data.drop(columns=target_column)  # Every column except target column
target = data[target_column]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(features, 
                                                    target,
                                                    test_size=0.2,
                                                    stratify=target  # Maintain target distribution
                                                   )

In [15]:
y_train.value_counts(normalize=True)

Class
0    0.601247
1    0.398753
Name: proportion, dtype: float64

In [16]:
y_test.value_counts(normalize=True)

Class
0    0.60095
1    0.39905
Name: proportion, dtype: float64

In [17]:
len(X_train) == len(y_train)

True

In [18]:
len(X_test) == len(y_test)

True

In [25]:
len(X_train)

3368

## Model Training

In [19]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=4)

In [20]:
knn.fit(X_train, y_train)  # Training the model

KNeighborsClassifier()

## Model Evaluation

In [21]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

In [39]:
spam = data['Class'] == 1
len(data[spam])

1679

## Train Accuracy

In [24]:
y_pred_train = knn.predict(X_train)  # Model Predictions using features from train data
y_pred_train

array([0, 0, 0, ..., 1, 0, 0], shape=(3368,))

In [26]:
y_train  # True values of spam/non-spam from the dataset

2071    0
4310    0
2285    0
1317    1
3471    0
       ..
2977    0
2919    0
286     1
4531    0
3441    0
Name: Class, Length: 3368, dtype: int64

In [32]:
predictions = (y_train == y_pred_train)  # Comparing true values with model's prediction to find accuracy
predictions  # Boolean Series object

2071     True
4310     True
2285     True
1317     True
3471     True
        ...
2977    False
2919     True
286      True
4531     True
3441     True
Name: Class, Length: 3368, dtype: bool

In [29]:
predictions.sum()  # Get only the correct predictions - total count of `True`.

np.int64(2863)

A prediction is correct if:

* model predicted as `spam` and true value is also `spam`
* model predicted as `non-spam` and true value is also `non-spam`

In [30]:
2863/3368  # Computing accuracy manually. Out of 3368 emails given to the model, 2836 were predicted correctly

0.8500593824228029

In [31]:
accuracy_train = accuracy_score(y_true=y_train, y_pred=y_pred_train)
print(accuracy_train)

0.8500593824228029

In [43]:
precision_train = precision_score(y_true=y_train, y_pred=y_pred_train, pos_label=1)
print(precision_train)

0.8258164852255054

In [44]:
recall_train = recall_score(y_true=y_train, y_pred=y_pred_train, pos_label=1)
print(recall_train)

0.7907669396872673

### Test Accuracy

In [47]:
y_pred_test = knn.predict(X_test)  # Predict using test data's features

In [42]:
accuracy_test = accuracy_score(y_true=y_test, y_pred=y_pred_test)
print(accuracy_test)

0.8111638954869359

In [45]:
precision_test = precision_score(y_true=y_test, y_pred=y_pred_test)
print(precision_test)

0.7706422018348624

In [46]:
recall_test = recall_score(y_true=y_test, y_pred=y_pred_test, pos_label=1)
print(recall_test)

0.75